# -*- coding: utf-8 -*-
"""31-07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SqMaLtzK_WYjzWuooqI015R-3FJtAb0w
"""

a = 46465.4
b = 45645.9

#teste de condição
if a > b:
  print(a)

if b > a:
  print(b)

palavra = 'pneumoultramicroscopicossilicovulcanoconiótico'

if len(palavra) > 5:
  print("Tem mais de 5 letras")

elif len(palavra)<5:
  print("Menos de 5 letras")

else:
  print("5 letras exatas")

print(f"A palavra tem {len(palavra)} letras")

a = 1
b = 2
c = 3
menor = a

#condições
if menor > b:
  menor = b

if menor > c:
  menor = c

if a == b or c == b or a == c:
  print("Existem dois numeros iguas e")

print("O menor é", menor)

#dados
nome = 'Felps'
idade = 479
senha = 'Tropidacris232'
i = 0

#analisar se é valido
if len(nome)>=4:
  print("Nome valido")
  i = i + 1

if  len(senha)>= 8:
  print("Senha valida")
  i = i + 1

if idade>=15:
  print("Idade valida")
  i = i +1


#conclusão
if i == 3:
  print("\nPode criar conta")

else:
  print("\nVocê não é real")

dificuldade = int(input("Escolha a dificuldade (de 1 a 10): "))
# Verificando se a dificuldade está correta:
if dificuldade > 10 or dificuldade < 1:
  quit()
# Definindo o número de tentativas com base na dificuldade:
tentativas_possiveis = 11 - dificuldade
# Perguntando a palavra para o usuário:
# Perguntando a palavra para o usuário:
palavra = input("Qual a palavra a ser decifrada? ")
# Tratando a palavra:
palavra = palavra.strip().lower()
# Perguntando o chute do usuário:
chute = input("Chute uma palavra: ")
# Tratando o chute:
acertou = palavra == chute
if acertou:
  print("Você acertou!")
else:
  print("Chute incorreto!")