# -*- coding: utf-8 -*-
"""Lab8-1108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-YyCtY8ws7AGfOeMd0NIQJm9TLebNlcu
"""

from sympy import sqrt
import math

""" Exercicio 1 - Sabendo que a área de uma circunferência é dada por , escreva um código que receba do teclado e exiba na tela . Utilize a constante pi fornecida pela linguagem."""

N = float(input())
Re = N * N * math.pi

print(f"A area da circunferencia é: {Re}")

"""Exercicio 2 - Dados os pontos e como entrada pelo teclado, escreva um código que exiba na tela a distância entre ambos

"""

X = float(input())
Y = float(input())
X1 = float(input())
Y1 = float(input())
Dist = sqrt((X1 - X) * (X1 - X) + (Y1 - Y) * (Y1 - Y))
Dist

x1= float(input())
y1 = float(input())
x2 = float(input())
y2 = float(input())

x3 = x1
y3 = y2

print(f"As coordenadas do vértice C são: [{x3, y3}]")

P = int(input())
B = int(input())
Bp = B / P
Rb = B % P
Bp = int(Bp)
print(f"Serão {Bp} por pessoa e restam {Rb}")

St = input().strip().lower()

print(St[0])

i = input().strip().lower()
j = input().strip().lower()

if len(i) >= 3 and len(j) >= 3:
  resultado = i[:3] + j[-3:]
  print(resultado)

else:
  print("Invalido")

u = int(input())
i = 2
primo = True

if u <= 1:
  primo = False

while i < u:
  if u % i == 0:
    primo = False
  i = i + 1


if primo == True:
  print("Sim")

else:
  print("Não")

h = int(input())
k = int(input())
i=2

while i <= k:
  if k %i == 0:
    print(i)

  i = i + 1

w = int(input())
i = 1
x = 1
y = 0
while i <= w:
  z = x + y
  print(z)

  x = y
  y = z

  i = i + 1

a = int(input())

N = a + a*11 + a*111 + a*1111

print(N)

a = int(input())
aa = int(str(a) * 2)
aaa = int(str(a) * 3)
aaaa = int(str(a) * 4)
N = a + aa + aaa + aaaa

print(N)