# -*- coding: utf-8 -*-
"""TI0408.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urEzYynI-pjo8gHjjUhGU5MXa5_gviLS
"""

cont = 0

while cont < 6:
  print(cont)
  cont = cont + 1

x = 0

while x <50 and x != 20:
  print(x)
  x += 1

somaTotal = 0
media = "Nenhuma media foi calculada"
quantNotas = 0
CalcMedia = True

while CalcMedia:
  nota = input("Insira a Nota: ")

  if nota == ".":
    CalcMedia = False

  else:
    somaTotal += float(nota)
    quantNotas += 1

  media = somaTotal/quantNotas
  print(f"Media: {media}3221.")

num = 0

print("Inicio")

for num in range(1,5,1):
  print(num)

print("Fim")

N = int(input())

for i in range(0, N+1, 2):
  if i != 0:
    print(f"{i} é par")

dificuldade = int(input("Escolha a Dificuldade (de 1 a 10): "))

if dificuldade > 10 or dificuldade < 1:
  quit()

tentativasPossiveis = 11 - dificuldade

palavra = input("Qual a palavra a ser decifrada? ")
palavra = palavra.strip().lower()

if palavra.isalpha():
  print("Pode começar!")
  Finalizado = False

else:
  print("Palavra proibida!")
  Finalizado = True

while not Finalizado and tentativasPossiveis:
  chute = input("Chute uma palavra: ")

  acertou = palavra == chute

  if acertou:
    print("Você acertou !!")
    Finalizado = True

  else:
    print("Chute incorreto!")
    tentativasPossiveis -= 1
    print(f"Você pode errar mais {tentativasPossiveis} vezes!")

  if Finalizado:
    print(f"A palavra era {palavra}.")

palavraString = input().strip().lower()
palavra = []

for letra in palavraString:
  palavra.append(letra)

palavra

dificuldade = int(input("Escolha a dificuldade (de 1 a 10): "))

#verificando se a dificuldade é valida
if dificuldade > 10 or dificuldade < 1:
  quit()

#Definindo o numero de tentativas
tentativasPossiveis = 20 - dificuldade

#Perguntando a palavra ao usuario
palavraString = input("Qual a palavra a ser decifrada? ").strip().lower()

#tratando a palavra
palavra = []

for letra in palavraString:
  palavra.append(letra)

palavra = list(set(palavra))

#iniciando o jogo/verificaão para inicio
if palavraString.isalpha():
  print("Pode começar!")
  Finalizado = False

else:
  print("Palavra proibida!")
  Finalizado = True

#Iniciando o loop
chutes = []
while not Finalizado and tentativasPossiveis:
  chute = input("Chute uma letra: ").strip().lower()

  #verificando se se encaixa nas especificações
  if len(chute) > 1:
    print("Chute uma letra! ")
    continue

  #verificando se está repetindo
  if chute in chutes:
    print("Chute repetido... ")
    continue

  #Adicionando chutes a lista de chute
  chutes.append(chute)
  chutes = list(set(chutes))

  #printando as descobertas
  for letra in palavraString:
    if letra in chutes:
      print(letra, end='')
    else:
      print('_', end='')
  #verificando acertos
  print()
  #Verificando se a lista de chutes tem todos os elementos da lista
  faltaLetra = False
  for letra in palavra:
    if letra not in chutes:
      faltaLetra = True

  if faltaLetra:
    if chute not in palavra:
      tentativasPossiveis -= 1
      print("Chute Incorreto!")
      print(f"Você pode errar mais {tentativasPossiveis} vezes!")
    else:
      print("Chute correto, ainda faltam letras!")
  else:
    print("Você Acertou!!")
    Finalizado = True

  #finalizado = terminado

if Finalizado and palavraString.isalpha():
  print(f'A palavra era "{palavraString}".')

n = 0

while n < 5:
  print("Go, do a crime.")
  n += 1

n = 1;
while n != -1:
  n = int(input())
  m = int(input())

  if n != -1:
    if n%m == 0:
      print(f"{n} é multiplo de {m}")

    else:
      print("Não é multiplo !")

  else:
    break;

n = int(input())
i = 0

while(i <= n):
  print(i)
  i += 1

n = int(input())
i = 1

while(i <=n):
  if(i%2 == 0):
    print(i)
  i += 1